version: "3.3"

services:
  butterfly_mysql:
    image: mysql
    container_name: butterfly_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - butterfly_mysql_backup:/docker-entrypoint-initdb.d
      - butterfly_mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=init
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  butterfly_phpmyadmin:
    depends_on:
      - butterfly_mysql
    image: phpmyadmin/phpmyadmin
    container_name: butterfly_phpMyAdmin
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./phpMyAdmin:/sessions
    environment:
      PMA_HOSTS: butterfly_mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root

  butterfly_redis:
    image: redis:alpine
    container_name: butterfly_redis
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    volumes:
      - ./redis:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_PASSWORD=redis_password

  butterfly_backend_http:
    depends_on:
      - butterfly_mysql
      - butterfly_redis
    image: prakasa1904/tps-py-api:latest
    container_name: butterfly_backend_http
    working_dir: /code/
    volumes:
      - ../:/code
      - /code/python_modules/ # Generate volume `python_modules` empty
    restart: always
    command: make dev-web-docker
    env_file:
      - ./.env
    ports:
      - 5000:5000

volumes:
  butterfly_mysql_backup:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker/mysql/restore
      o: bind
  butterfly_mysql_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker/mysql/volume
      o: bind
