version: "3"

services:
  backend:
    image: python:3.7.3
    working_dir: /code/
    volumes:
      - ../:/code
    restart: always
    command: make dev-web-docker
    env_file:
      - ../.env
    ports:
      - 5000:5000
